### ISSUE TITLE
WriteLogEntriesRequest API is called per a log entry

### ISSUE THREAD

**Issue by ikenox** [googleapis/java-logging-logback#134] opened 2020-07-09 16:38 UTC
Hi, I use this library in my GCP project App Engine application, and I found that the quota `Log ingestion requests` is easily exhausted when load testing.

When a log entry is appended, the log is wrapped as singleton list, and it is passed to google-cloud-logging library.
https://github.com/googleapis/java-logging-logback/blob/master/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L232

Finally the singleton list seems to be converted to one `WriteLogEntriesRequest`.
This means one log entry causes one [WriteLogEntriesRequest API](https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.v2#writelogentriesrequest) call.
https://github.com/googleapis/java-logging/blob/8cbf0af1c63dd14392bd819c9a33e0141d7aad2f/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java#L510

I think it's better to support batch send option in order to reduce request number and save `Log ingestion requests` quota.
Is my idea correct?

**Comment by nicoleczhu** [comment] 2021-01-27 00:39
This library intentionally doesn't support batch logs. Though, I can see an implementation down the line to allow batching, where we: 
1. Override `append()` to instead store logs in a `ConcurrentHashMap`.
2. Introduce a BUFFER variable (defaults to 1), that can be reset to allow batching up to `n` logs at a time.
3. And once FLUSHLEVEL or BUFFER limit is reached, we can simply call `logging.write(buffered_logs, ...)`.

This would be a breaking change, marking this feature request as a P3 for now. 

In the meantime, @ikenox you may have an easier time directly using the [java-logging](https://github.com/googleapis/java-logging) library. 

The benefit is that you can batch write logs [instructions](https://cloud.google.com/logging/docs/api/tasks/creating-logs#writing_log_entries) as well as set your own timestamps (maybe per system time rather than api call time), which gives you more granularity during load testing.

**Comment by Daniel-Sanche** [comment] 2021-02-02 20:15
Building off of what Nicole said, logs will only be sent in individual API calls if their severity is at or above the [flushLevel](https://github.com/googleapis/java-logging-logback#usage) (which defaults to `ERROR`). Anything below the flush level will be internally batched (assuming [`writeSynchronicity` is `ASYNC`](https://github.com/googleapis/java-logging-logback/blob/b6bc7291abdcd2bc7d3b808d8202d4c7098cc639/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L235)). As of [v0.120.0](https://github.com/googleapis/java-logging-logback/pull/320), you should be able to set `flushLevel=OFF` to prevent instant-flushing entirely.

I'm going to close this as a duplicate of https://github.com/googleapis/java-logging-logback/issues/133, but feel free to re-open if you want to discuss this further!

**Comment by hwellmann** [comment] 2021-06-07 12:18
Please reopen, this is **not** a duplicate of #133.

WIth #133, you can prevent flushing, but you still can't batch log entries and reduce the Log ingestion requests.

The _instructions_ link in https://github.com/googleapis/java-logging-logback/issues/134#issuecomment-767926771 is broken, see [Write structured logs](https://cloud.google.com/logging/docs/reference/libraries#write_structured_logs) instead.

**Comment by artemptushkin** [comment] 2021-06-25 11:49
I'd like to join @hwellmann this is still a **viable** request. With the suggestion to adjust flushing we just **postpone** set of requests but it does one by one.

I would expect: if it sends on _flush_ then merge all the entries into a single one, but it looks like it doesn't work like this.
See the screenshot, it's always one entry when I sent 1000 in a loop, and Stackdriver logs prove it
![image](https://user-images.githubusercontent.com/22632802/123419988-36355e80-d5bb-11eb-968a-edb20e7f2a47.png)

Just to make it clear, by batching on logback side I'd like to see call like this https://cloud.google.com/logging/docs/reference/libraries#logging_write_log_entry-java with `Logging #write(Iterable<LogEntry>)` in use.

Would really appreciate it if you can implement this, it burns the quote

**Comment by minherz** [comment] 2021-08-11 10:25
The provided comments include somewhat different situations. I would like to try and summarize the use cases in order to identify the expected behavior.

As it was mentioned the way the log entry writing is implemented depends on the way the logger synchronization is configured. If [synchronization](https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java#L95) is set to [Synchronicity.SYNC](https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/Synchronicity.java#L24) the collection of log entries is sent synchronously when [LoggingImpl.write()](https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingImpl.java#L687) is invoked. Given each call sends a single or few log entries in an event of the load test it is easy to exhaust the quota for the API calls. The referenced [appender code](https://github.com/googleapis/java-logging-logback/blob/master/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L232) clearly sends only one log entry.
@ikenox, can you please confirm that the application does not explicitly configure synchronous logging? If it does, can you change (or remove) this configuration and see if you still has a problem with API call quota?

@artemptushkin and @hwellmann , reading your comments I could not understand what is a problem you report. Unless it is the same as in the issue description, can you provide a use case and reproducing steps please?

**Comment by minherz** [comment] 2021-08-11 18:32
@artemptushkin you are correct for SYNC case. However, for ASYNC case the log entries will be batched following the batching configuration in gax library. It does not happened on a call to flush. The name is misleading. The flush speeds up sending collected log entries as soon as possible by the gax batching logic.

For SYNC case I do not see how log aggregation can be possible. If you request SYNC but you ask to send **single** log entry, there is no place for aggregation. The single entry is sent as requested.

Logging library and appender have the synchronization flag set to ASYNC by default. Setting it to SYNC means that a caller explicitly asked to send all log entries they provided to the logger (or appender) immediately on the call. A developer has to decide what is desired: \1 a promised API call on invocation of the logger or \2 implicit background sending which leaves places to aggregation and other optimizations.

So the expectations for SYNC behavior when a single log entry is provided do not match the configured functionality.

**Comment by artemptushkin** [comment] 2021-08-11 19:15
Sync is clear, it's just an example. Certainly, ASYNC is expected to be updated.

I stand on the fact that I had behavior A on production then I debugged and found this, code confirms. Could you refer to that gax usage you're writing about?

> by the gax batching logic.

then gax must merge log entries but I didn't see this before sending.

Or, please, check the code I refer to point where I'm wrong

**Comment by minherz** [comment] 2021-08-12 11:07
The code referenced in your comments [1](https://github.com/googleapis/java-logging-logback/issues/134#issuecomment-868443105) and [2 ](https://github.com/googleapis/java-logging-logback/issues/134#issuecomment-896739622) shows the direct call up to the depth of 3. It does not show that asynchronous operation does not batch multiple log entries.
I am not sure to what you reference as "behavior A", but you can look at GrpcLoggingRpc [constructor](https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/spi/v2/GrpcLoggingRpc.java#L97) for batching and transport channel configuration. All asynchronous calls are further handled by gax [library](https://github.com/googleapis/gax-java). The batching for logging is configured in the [LoggingServiceV2StubSettings.java](https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java#L647).

If you are still convinced that batching in asynchronous mode does not work, please compose a minimal application that, for your opinion, demonstrates this.

Thank you.

**Comment by artemptushkin** [comment] 2021-08-18 12:28
Seems like it's enabled by default here `com.google.api.gax.batching.BatchingSettings #newBuilder`

For the history, the reference is: `com.google.cloud.logging.spi.v2.GrpcLoggingRpc #write` calls `com.google.api.gax.rpc.BatchingCallable futureCall(RequestT request, ApiCallContext context)` the latter depends on enabling of the property, which is true be default and never changes to false.

It's hard to debug async code, so I rely on the code and your @minherz statement. I might be wrong with assumptions.

At least this discussion satisfies the problem: there is batching that is used by grpc in gax library. I think, that it makes no sense then to update Logback with additional batching logic.

As I see it's documented as well https://cloud.google.com/logging/docs/setup/java#defaults without details, but sufficient.

The ticket can be closed for me so far till any other issues/evidences.

**Closed** 2021-08-19 05:22 UTC
Labels: type: feature request, api: logging, priority: p3
