### ISSUE TITLE
gcp-logging error

### ISSUE THREAD

**Issue by nidhisri99** [googleapis/java-logging-logback#577] opened 2021-10-20 09:50 UTC
I am getting this error 
```
Exception in thread "main" java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:96)
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:306)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:73)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:214)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:221)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:204)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:132)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:142)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:61)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:55)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:561)
	at com.google.cloud.logging.LoggingOptions.getLoggingRpcV2(LoggingOptions.java:129)
	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:117)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:46)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:41)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:541)
	at com.google.cloud.logging.logback.LoggingAppender.getLogging(LoggingAppender.java:252)
	at com.google.cloud.logging.logback.LoggingAppender.start(LoggingAppender.java:214)
	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:130)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:91)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:203)
```	
logback.xml file looks like this:
 
```
<configuration>
	<include resource="org/springframework/boot/logging/logback/defaults.xml"/>
	<include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
	<include resource="org/springframework/cloud/gcp/logging/logback-appender.xml"/>

	<root level="INFO">
		<appender-ref ref="CONSOLE"/>
		<appender-ref ref="STACKDRIVER"/>
	</root>
</configuration>
```

**Comment by nidhisri99** [comment] 2021-10-21 13:13
Hi Minherz,
I was trying to get the logs of my spring boot application in GCP stackdriver. I am using java8 runtime

I have added the below dependence in pom.xml 
<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-logging</artifactId>
        </dependency>
AND 
I am using the GOOGLE_CLOUD_PROJECT (ProjectId that is in GCP) and GOOGLE_APPLICATION_CREDENTIALS as environment variables.

when I try to run, I am getting the above error "Exception in thread "main" java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not found"

I also tried adding  the netty dependencies, but nothing worked out. 

If any other details required please ask. Thanks in advance

**Comment by minherz** [comment] 2022-01-17 10:07
@nidhisri99 without a minimal application we cannot reproduce the problem. judging by exception the problem is with discovering configuration file and is not directly related to the library behavior. We have recently been reported a similar problem (#571). It describes NPE thrown at initialization due the fact that Jetty Web Server looks for configuration along a path that is different from one we provide in our examples.
Given our examples are intended for use in vanilla Java applications, it is up to a developer to adjust the instructions of the example.
If you think that the problem is in the library, please provide us with a simple netty-based application including pom.xml and all relevant files. We will try to run and debug your example in our environment to validate the error. We cannot construct such application based on the snippets that your provided in this issue.

**Comment by minherz** [comment] 2022-01-28 10:33
I close the issue for now. Please, reopen it when you add more information, so we can address it accordingly.

**Closed by minherz** 2022-01-28 10:33 UTC
Labels: type: question, api: logging, priority: p3, lang: java
